In [1]:
import cv2
import numpy as np

def cv_show(img,name="image"):
    cv2.imshow(name,img)
    cv2.waitKey() #ms 不输入代表任意键销毁窗口
    cv2.destroyAllWindows()

In [13]:
img = cv2.imread("01_Picture/18_House.jpg")
gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

sift = cv2.xfeatures2d.SIFT_create()
kp = sift.detect(gray, None) # None为mask=None
print(kp[:3])

cv2.drawKeypoints(image=img, keypoints=kp, outImage=img) # 
cv_show(img)

[<KeyPoint 000001C622824FC0>, <KeyPoint 000001C622532990>, <KeyPoint 000001C622532A20>]


In [19]:
kp, dst = sift.compute(gray, kp)
print(np.array(kp).shape, kp[:3])
print(gray.shape, dst.shape, dst)

(6827,) [<KeyPoint 000001C622824EA0>, <KeyPoint 000001C622824F60>, <KeyPoint 000001C622824F30>]
(800, 1200) (6827, 128) [[  0.   0.   0. ...   0.   0.   0.]
 [  0.   0.   0. ...   0.   0.   0.]
 [  5.  29. 103. ...  40. 112.  57.]
 ...
 [ 11.   9.   3. ...  51.  23.  17.]
 [ 50.  46.  22. ...   0.   0.   0.]
 [  0.   0.   0. ...  25.  60. 147.]]
