In [ ]:
import numpy as np

# 如何从数组np.arange(15)中提取5到10之间的所有数字？ 

In [3]:
import numpy as np
array = np.arange(15)
index = np.where((array>=5) & (array<=10))
print(array[index])

[ 5  6  7  8  9 10]


# 如何交换数组np.arange(9).reshape(3,3)中的第1列和第2列？

In [4]:
import numpy as np
a = np.arange(9).reshape(3,3)
a = a[:,[1,0,2]]
print(a)

[[1 0 2]
 [4 3 5]
 [7 6 8]]


# 如何交换数组np.arange(9).reshape(3,3)中的第1行和第2行？

In [5]:
import numpy as np
a = np.arange(9).reshape(3,3)
a = a[[1,0,2],:]
print(a)

[[3 4 5]
 [0 1 2]
 [6 7 8]]


# 如何获取数组a = np.array([1,2,3,2,3,4,3,4,5,6])和数组b = np.array([7,2,10,2,7,4,9,4,9,8])之间的共同元素？

In [6]:
import numpy as np
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
c = np.intersect1d(a,b)
print(c)

[2 4]


# 如何查找数组np.array([1,2,3,2,3,4,3,4,5,6])中的唯一值的数量？

In [7]:
import numpy as np
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.unique(a)
print(len(b))

6


# 如何找到二维数组np.arange(9).reshape(3,3)每一行中的最大值？

In [8]:
import numpy as np
a = np.arange(9).reshape(3,3)
b = np.max(a,axis=1)
print(b)

[2 5 8]


# 如何计算数组a = np.array([1,2,3,2,3,4,3,4,5,6])和数组b = np.array([7,2,10,2,7,4,9,4,9,8])之间的欧式距离？

In [9]:
import numpy as np
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
dist = np.sqrt(np.sum(np.square(a - b)))
print(dist)

12.529964086141668


# 如何知道数组np.array([7,2,10,2,7,4,9,4,9,8])中的第二大值是多少？

In [10]:
import numpy as np
a = np.array([7,2,10,2,7,4,9,4,9,8])
a_sorted = np.sort(a) # 对数组进行升序排序
second_max = a_sorted[-2] # 取倒数第二个元素
print(second_max)

9


# 如何知道数组np.array([7,2,10,2,7,2,4,9,4,9,8])中出现频率最高的值是什么？

In [11]:
import numpy as np
a = np.array([7,2,10,2,7,2,4,9,4,9,8])
counts = np.bincount(a) # 对数组中的每个元素计数
max_freq = np.argmax(counts) # 找出计数最大的元素
print(max_freq)

2
